version: 2
jobs:
  build:
    working_directory: ~/src/main/

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout:
          path: ~/

      - run:
          name: Build
          command: javac Main.java

      - run:
          name: Test
          command: java test/RouteManagerTest.java